Update action admin
WildCodeSchool/2022_09_PHP_Lyon_aeterna_fabula pull request #22
Opened 2022-11-08 16:28 UTC by emainguelag

admin action update + add without PDOException manage

2022-11-08 16:55 UTC, aldaitzwild requested changes

2022-11-08 16:55 UTC, aldaitzwild commented on src/Model/ActionManager.php
> +        $statement->bindValue('owner_id', $action['owner_id'], PDO::PARAM_STR);
This should be a INT

2022-11-08 16:55 UTC, aldaitzwild commented on src/Model/ActionManager.php
> +        $statement->bindValue('target_id', $action['target_id'], PDO::PARAM_STR);
Same Here

2022-11-08 16:55 UTC, aldaitzwild commented on src/Model/ActionManager.php
> +        $statement->bindValue('owner_id', $action['owner_id'], PDO::PARAM_STR);
Here too

2022-11-08 16:55 UTC, aldaitzwild commented on src/Model/ActionManager.php
> +        $statement->bindValue('target_id', $action['target_id'], PDO::PARAM_STR);
I guess you get the point

2022-11-08 16:55 UTC, aldaitzwild commented on src/View/Action/admin_show_action.html.twig
> +		<h2>
I wonder where this tag h2 ends ...

2022-11-08 19:26 UTC, emainguelag commented
5 errors corrected into the new push on this branch. Thank you!

2022-11-09 08:24 UTC, aldaitzwild approved these changes

2022-11-09 08:24 UTC, merged