Add historic
WildCodeSchool/2022_09_PHP_Lyon_aeterna_fabula pull request #25
Opened 2022-11-09 12:17 UTC by 79Inaf

Added table historic + it's generated in SQL with the historic of the player + No back button + trumpet sound

2022-11-09 12:51 UTC, aldaitzwild requested changes

2022-11-09 12:51 UTC, aldaitzwild commented on src/Controller/ChapterController.php
> +        $historicManager->historicInsert($action);
You should'nt call this if action is null

2022-11-09 12:51 UTC, aldaitzwild commented on src/Controller/HistoricController
> +// }
A full file of dead code ! Congrats

2022-11-09 13:41 UTC, aldaitzwild requested changes

2022-11-09 13:41 UTC, aldaitzwild commented on src/Model/HistoricManager.php
> +    public function historicInsert(int | null $actionId): void
No $action should'nt be allowed to be null

2022-11-09 15:13 UTC, aldaitzwild requested changes
Conflict With Dev

2022-11-09 16:40 UTC, aldaitzwild requested changes

2022-11-09 16:40 UTC, aldaitzwild commented on af_database.sql
> +TRUNCATE historic;
It should be TRUNCATE TABLE

2022-11-10 08:31 UTC, 79Inaf commented on af_database.sql
> +TRUNCATE historic;
I fixed the problem on the file af_database.sql

2022-11-10 09:15 UTC, closed without merging

2022-11-10 09:20 UTC, charlietoussaint commented
We decided to close this PR for a new one with CSS, advised fixed are implemented